### ISSUE TITLE
Please provide a full example

### ISSUE THREAD

**Issue by RezaRahmati** [p-fedyukovich/nestjs-google-pubsub-microservice#10]
Hi there

Would you please provide a full example in this repo or medium website. For example it's not clear where to put that `const client = xx ` and ...

It will be very helpful

Thank you in advance

**Comment by p-fedyukovich** [comment]
You can read tests in following [directory](https://github.com/p-fedyukovich/nestjs-google-pubsub-microservice/blob/cc01e4c42972fe19a89087e4986161057cba47f6/tests/src/gc-pubsub.controller.ts)
