### ISSUE TITLE
multiple subscribers + Listen to a topic  - Difference between emit and send

### ISSUE THREAD

**Issue by Bamorem** [p-fedyukovich/nestjs-google-pubsub-microservice#12]
Hi, Is it possible to have multiple subscriptions without having to setup multiple app.connectMicroservice().

Our goal is to set a topic per action, for example one topic for create-user another one for update-user....

Plus we need to listen to a specific pattern example @MessagePattern('create-user'). By doing this it means sending a message like this :

```
const client: ClientProxy = new GCPubSubClient({
      topic: 'create-user',
      client: {projectId: 'my-project'},
    });
    try {
      return client.emit('create-user', data);
    } finally {
      client.close();
    }
```

As you can see, i have to specify 'create-user' as a topic and as well has message pattern. So is it possible to listen to a topic and not a pattern ?

Also last question, what is the difference between client.emit() and client.send() . Not really clear from the docs.

Summary:
 - Best way to have multiple subscribers
 - How to listen to a topic not a pattern
 - what is the difference between client.emit() and client.send()

Thanks

**Comment by p-fedyukovich** [comment]
Hi, current implementation implies that one client/server handles two pairs of topic/subscription
Client sends messages to single server topic, pubsub sends messages to server subscription. If it message is `MessagePattern` then once the server handles message it sends back a reply message to client topic, and again pubsub sends the reply message to client subscription which the client listens to.

It was original idea of this PubSub microservice. There are others implementations which allows to have multiple subscriptions to listen for a single instance of a server.

`client.emit()` is for event based async pattern, when a client is not supposed to get reply from a server
`client.send()` is message sync pattern, it allows to handle response from a server

Summary:
* `client.emit('create-user', data)` means publish message to pre configured topic message with "event type" `create-user` inside a message
* Single server listens only one subscription which is declared in PubSub strategy options
* You can read about the difference of emit and send patterns in [NestJs docs ](https://docs.nestjs.com/microservices/basics#patterns)
