### ISSUE TITLE
add support to send attributes along with data object.

### ISSUE THREAD

**Issue by IrfanAli17899** [p-fedyukovich/nestjs-google-pubsub-microservice#14]
it would be nice and awesome if attributes can be sent along with the messages, right now its hardcoded from the lib it self but would be great if it can be extended.

**Comment by p-fedyukovich** [comment]
Hello, unfortunately in order to achieve it need to change `data` parameter interface which may cause issues for existing clients of the package. Original NestJS microservice 
```
send<TResult = any, TInput = any>(pattern: any, data: TInput): Observable<TResult>;
emit<TResult = any, TInput = any>(pattern: any, data: TInput): Observable<TResult>;
```
does not provide any additional parameters to implement
