### ISSUE TITLE
Support @google-cloud/pubsub version 3

### ISSUE THREAD

**Issue by moshekrup** [p-fedyukovich/nestjs-google-pubsub-microservice#15]
Is there any plan to add support for google/pubsub version 3?

**Comment by p-fedyukovich** [comment]
Yes, sure. Will be bumped soon

**Comment by moshekrup** [comment]
I forgot to mention, but it will be great to update from nestJS version 8 to 9 :)
Thanks!

**Comment by p-fedyukovich** [comment]
Done in #16
