### ISSUE TITLE
Only usable with Pub/Sub Admin permissions

### ISSUE THREAD

**Issue by organic-data** [p-fedyukovich/nestjs-google-pubsub-microservice#17]
This microservice only works with Pub/Sub Admin permission, but in many use cases, this does not follow the least permission policy.
For some reason, it tries to create a topic and subscription if they do not exist, would be great if this would be optional.

**Comment by p-fedyukovich** [comment]
Hi, thanks for feedback, good point, will add soon option parameter which would disable automatic topics and subscription creation

**Comment by p-fedyukovich** [comment]
Added in  #19
