### ISSUE TITLE
Support for nest v10

### ISSUE THREAD

**Issue by ssipos90** [p-fedyukovich/nestjs-google-pubsub-microservice#31]
Hi,

Cool project!
Are there any plans in supporting nest v10?

Thanks

**Comment by p-fedyukovich** [comment]
Hi, sure will be done soon!

**Comment by oscarojeda** [comment]
Hi there, how soon??

**Comment by p-fedyukovich** [comment]
On this weekend

**Comment by p-fedyukovich** [comment]
Done #33

**Comment by oscarojeda** [comment]
Thanks so much for your contributions to the community
