### ISSUE TITLE
Why is server.send called when only listening?

### ISSUE THREAD

**Issue by ggpt-labs** [p-fedyukovich/nestjs-google-pubsub-microservice#34]
I've got a weird error, so far I only implemented this listener:

```
@MessagePattern({ cmd: 'test' })
listen(@Payload() payload: any, @Ctx() context: GCPubSubContext) {
  console.log('Payload:', payload);
  console.log('Context:', context);
}
```

And the server is configured with _topic_, _subscription_, and a client (_keyFile_, _projectId_).

Whenever a message arrives, I also get this error:
```
Error: A name must be specified for a topic.
    at PubSub.topic (/Users/me/myproject/node_modules/@google-cloud/pubsub/src/pubsub.ts:1435:13)
    at GCPubSubServer.sendMessage (/Users/me/myproject/node_modules/nestjs-google-pubsub-microservice/lib/gc-pubsub.server.ts:223:7)
    at publish (/Users/me/myproject/node_modules/nestjs-google-pubsub-microservice/lib/gc-pubsub.server.ts:215:22)
    at /Users/me/myproject/node_modules/@nestjs/microservices/server/server.js:49:31
    at processTicksAndRejections (node:internal/process/task_queues:77:11)
```

Which is weird as '/@nestjs/microservices/server/server.js:49' belongs to the 'send' function and I'm not trying to send anything. Unfortunately there is also no hint to any app code in the stack trace.

Any ideas?

**Comment by p-fedyukovich** [comment]
Hi, probably you message doesn't contain topic name which is used for reply to client. Usually it's `replyTopic` on client config

**Comment by p-fedyukovich** [comment]
You use Nestjs microservice message pattern which implies that a client sends event to a server, server processes it and send response message back to the client. In your case it seems that the client doesn't have configured `replyTopic` parameter that's why server can't respond to the client. Make sure that you configured client properly and server pubsub subscription doesn't have old message without `replyTo` attribute.

**Comment by p-fedyukovich** [comment]
So here are important configs for both sides:
Client:
* `topic` - pubsub topic that belongs to server, subscription of this topic is listened by a server
* `replyTopic` - pubsub topic that belongs to client, server sends responses to this topic, subscription of this topic is listened by a client
* `replySubscription` - pubsub subscription that belongs to client, this is subscription that described above
Server:
* `topic` - pubsub topic that belongs to server, subscription of this topic is listened by a server
* `subscription` - pubsub subscription that server listens to

**Comment by p-fedyukovich** [comment]
Please read docs carefully https://github.com/p-fedyukovich/nestjs-google-pubsub-microservice#options

**Comment by p-fedyukovich** [comment]
`replyTopic` is client only

**Comment by p-fedyukovich** [comment]
In your case 
```typescript
export class GCPubSubController implements OnApplicationShutdown {
  client: ClientProxy;

  constructor() {
    this.client = new GCPubSubClient({
      topic: configService.get<string>('GCLOUD_TOPIC'),
      replyTopic: configService.get<string>('GCLOUD_CLIENT_TOPIC'),
      replySubscription: configService.get<string>('GCLOUD_CLIENT_SUBSCRIPTION'),
      noAck: false,
      client: {
        projectId: 'microservice',
      },
    });
  }

  onApplicationShutdown() {
    return this.client.close();
  }
}```

**Comment by p-fedyukovich** [comment]
Again, a message which is handled by `@MessagePattern` decorator must contain `replyTo` attribute in order to send response back to original message producer. Otherwise use `@EventPattern` decorator

**Comment by p-fedyukovich** [comment]
Yes, it's because a message contains `id` attribute, which should be eliminated for `@EventPattern`
