### ISSUE TITLE
Multiple topic subscription and healthcheck

### ISSUE THREAD

**Issue by foxted** [p-fedyukovich/nestjs-google-pubsub-microservice#5]
Hi there,

Interested in using the package, I was wondering a couple thing, maybe you can help me out: 

- How would I subscribe to multiple topics (auto-discovery based on my controllers)
- How would I ensure the subscriptions are healthy (maybe using @nestjs/terminus)

Thanks!

**Comment by p-fedyukovich** [comment]
Hi

> How would I subscribe to multiple topics (auto-discovery based on my controllers)

A microservice server can only subscribe to a single subscription, which is passed in options. Could you explain this "auto-discovery based on my controllers"?

> How would I ensure the subscriptions are healthy (maybe using @nestjs/terminus)

There is no way to do that yet

**Comment by foxted** [comment]
Fair enough. Thanks for the reply. I went with an alternative, using push subscriptions via HTTPS for the time being.

**Comment by p-fedyukovich** [comment]
> Fair enough. Thanks for the reply. I went with an alternative, using push subscriptions via HTTPS for the time being.

You are welcome. If efficiency and throughput of message processing is not critical then it's good solution.
